# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MMS Studio
email: linmjnz@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  MMS Studio is a boutique Shopify development studio, specializing in custom Shopify sites. We are dedicated to providing high-quality, tailored solutions for your e-commerce needs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mms-studio.co.nz/" # the base hostname & protocol for your site, e.g. http://example.com

introduction:
  title: "Hi! 👋🏼 I'm Jason 🦸🏼‍♂️"
  education: "Graduated from Lincoln University with a Master of Applied Computing 🎓"
  content_one: "Shopify developer with 6+ years of experience 👨‍💻"
  content_two: "Specialize in creating custom Shopify sites that are tailored to your unique needs ♾️"
marquee_content: [
  "✨ Welcome to MMS Studio | Your go-to boutique for custom Shopify sites ✨",
  "🚀 6+ years Shopify expertise 🚀",
  "💡 Shopify Specialist | Custom Solutions | Theme Crafting 💡"
]

site_name: MMS Studio
author: Jason Lin
position: Founder / Developer
studio_url: mms-studio.co.nz
author_intro: "Shopify developer with 6+ years of experience, specializing in building custom Shopify websites tailored to unique business needs. Skilled in theme customization, performance optimization, and user-focused design. Ready to help bring any e-commerce vision to life."
author_bio: "Jason - Senior Shopify developer based in New Zealand🇳🇿, with over 6 years of experience working at local Shopify agencies. I'm passionate about freelancing and offers high-quality Shopify development services at more affordable rates."
author_sub_bio: "Always eager to grow by tackling new challenges, from small tasks to large-scale projects. Skilled in the following areas:"
services: [
  "Shopfiy Store Setup",
  "Shopify Theme Customization",
  "Shopify App Integration",
  "Shopify Store Maintenance",
  "Shopify Store Support",
  "Shopify SEO Optimization"
]
author_image: "https://cdn.prod.website-files.com/5a6a34c2920f950001f51775/67ff781d6493a0e4699efac3_T36Mtazsalt9Jrj2mQ-3EHnFVdwyYML8lvgIaVMc7Z0.webp"
education:
  - title: "Master's degree, Applied Computing"
    institution: "Lincoln University"
    year: Oct 2023 - Nov 2024
    logo: "https://media.licdn.com/dms/image/v2/D560BAQHs-BB5uuLAlQ/company-logo_100_100/company-logo_100_100/0/1689044544278/lincolnuninz_logo?e=1750896000&v=beta&t=I-PXDx1v-QNvKf46XNfgQ2UHn28NUvnys0wA9H6nqZE"
  - title: "Associate's degree, Web & UX Design"
    institution: "Yoobee College of Creative Innovation"
    year: 2018 - 2019
    logo: "https://media.licdn.com/dms/image/v2/C560BAQH4JmT10mR5rA/company-logo_100_100/company-logo_100_100/0/1644871039011/yoobeecolleges_logo?e=1750896000&v=beta&t=_o8_HTEJ-3wJLuPBR4nD4euqQpSR7tOoZy4aYoyPWdg"

experience:
  - title: "Senior Developer"
    company: "Moustache Republic"
    year: May 2024 - Present
    logo: "https://media.licdn.com/dms/image/v2/C560BAQFht5wFD32lsg/company-logo_100_100/company-logo_100_100/0/1634619657208/moustache_republic_logo?e=1750896000&v=beta&t=bq2500-qi8Ssown8wI2DQiqxtONO1ImN0XiJKqU-9EU"
  - title: "Senior Web Developer"
    company: "Pocket Square"
    year: January 2023 - May 2024
    logo: "https://media.licdn.com/dms/image/v2/C4D0BAQGju6L-P6emBA/company-logo_100_100/company-logo_100_100/0/1639692351635/pocket_square_logo?e=1750896000&v=beta&t=YGRBs8BoHrli7lNtIE7-GWeo4A57n0vsk-429Rnfqcs"
  - title: "Senior Developer"
    company: "Moustache Republic"
    year: May 2019 - January 2023
    logo: "https://media.licdn.com/dms/image/v2/C560BAQFht5wFD32lsg/company-logo_100_100/company-logo_100_100/0/1634619657208/moustache_republic_logo?e=1750896000&v=beta&t=bq2500-qi8Ssown8wI2DQiqxtONO1ImN0XiJKqU-9EU"

certification:
  - title: Liquid Storefronts for Theme Developers - Verified Skill Badge
    institution: "Shopify"
    year: Issued Nov 2024
    logo: https://media.licdn.com/dms/image/v2/D560BAQH9Y3IDQjuPSw/company-logo_100_100/company-logo_100_100/0/1737143878716/shopify_logo?e=1750896000&v=beta&t=niqip8zzJgsRPjhcBb8Uyb5KEQ_wHX5HF6h6XHOA254


social_links:
  - label: "UnicornFactory"
    url: "https://www.unicornfactory.nz/profiles/jason-lin"
  - label: "LinkedIn"
    url: "https://www.linkedin.com/in/jason-l-81824417b/"

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
